#!/usr/bin/env python

import os,json

datefile = os.path.join(os.getenv("datadir"),"data.json")
aggregatedfile = os.path.join(os.getenv("datadir"),"data-monthly.json")

with open(datefile,"r", encoding='utf-8') as f:
    data = json.load(f)

dataa = {}
for (ort,m) in data.items():
    print(ort)
    a = {}
    for (t,v) in m.items():
        d = t[:7]
        try:
            v = 1.0 * v
            n = 1

        except:
            v = 0
            n = 0

        if not d in a:
            a[d] = { "v": 0, "n": 0 }

        a[d]["v"] += v
        a[d]["n"] += n

    for (d,vn) in a.items():
        a[d] = vn["v"] / vn["n"] if vn["n"] > 0 else 0

    dataa[ort] = a

with open(aggregatedfile,"w") as f:
    json.dump(dataa,f,indent=2,sort_keys=True)
