#!/usr/bin/env python3

import requests, os, time

base_url = "https://inters.bayern.de/luft/messwertarchiv/NO2_{}.xlsx"

def getfile(tag):
    url = base_url.format(tag)
    filename = os.path.join(os.getenv("datadir"),f"NO2_{tag}.xlsx")
    print(f"Retrieve {url} ...")
    response = requests.get(url)
    if response.status_code == 200:
        with open(filename, "wb") as f:
            f.write(response.content)
        print(f"✔ got: {filename}")
        time.sleep(1)
        return True
    else:
        print(f"✖ no file {filename} found (Status: {response.status_code})")
        return False

year = 1980
while getfile(year):
    year += 1

month = 1
while True:
    tag = f"{year}_{month:02d}"
    if not getfile(tag):
        break

    month += 1
    if month > 12:
        year += 1
        month = 1
