#!/usr/bin/env python

import os

for tag in ["month","year"]:
    srcfile = os.path.join(os.getenv("htmldir"),f"{tag}ly.html")
    tgtfile = os.path.join(os.getenv("docsdir"),f"{tag}ly.html")
    datafile = os.path.join(os.getenv("datadir"),f"data-{tag}ly.json")

    with open(srcfile,"r") as s:
        with open(datafile,"r") as d:
            with open(tgtfile,"w") as t:
                print(f"creating {tgtfile}")
                data = d.read()
                t.write(s.read().replace('NO2NO2NO2',f"no2 = {data}"))

