#!/usr/bin/env python

import os
srcfile = os.path.join(os.getenv("htmldir"),"index.html")
tgtfile = os.path.join(os.getenv("docsdir"),"monthly.html")
datafile = os.path.join(os.getenv("datadir"),"data-monthly.json")

with open(srcfile,"r") as s:
    with open(datafile,"r") as d:
        with open(tgtfile,"w") as t:
            data = d.read()
            t.write(s.read().replace('NO2NO2NO2',f"no2 = {data}"))
